# Generated by Django 3.2.15 on 2022-09-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='사용자 아이디')),
                ('password', models.CharField(max_length=256, verbose_name='사용자 비밀번호')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='사용자 닉네임')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='사용자 계정 생성일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용자 활성상태')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 계정')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
